theme: jekyll-theme-cayman

title: Huiwen Wu
description: Applied Math Ph.D Candidate in UC Irvine
email: fairycloudsi@gmail.com
sitemap: true

author: 
        name: Huiwen Wu

social-network-links:
        email: "fairycloudsi@gmail.com"
        github: "fairycloudsi"

