theme: jekyll-theme-cayman

title: Huiwen Wu
description: Applied Math Candidate in UC Irvine

author: 
        name: Huiwen Wu

social-network-links:
        email: "fairycloudsi@gmail.com"
        github: "fairycloudsi"

